---
title: "Folland_Exp"
author: "Quinn Batten"
date: "February 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(car)
library(lattice)
library(methods)

#function
summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
                      conf.interval=.95, .drop=TRUE) {
    library(plyr)

    # New version of length which can handle NA's: if na.rm==T, don't count them
    length2 <- function (x, na.rm=FALSE) {
        if (na.rm) sum(!is.na(x))
        else       length(x)
    }

    # This does the summary. For each group's data frame, return a vector with
    # N, mean, and sd
    datac <- ddply(data, groupvars, .drop=.drop,
      .fun = function(xx, col) {
        c(N    = length2(xx[[col]], na.rm=na.rm),
          mean = mean   (xx[[col]], na.rm=na.rm),
          sd   = sd     (xx[[col]], na.rm=na.rm)
        )
      },
      measurevar
    )

    # Rename the "mean" column    
    datac <- rename(datac, c("mean" = measurevar))

    datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean

    # Confidence interval multiplier for standard error
    # Calculate t-statistic for confidence interval: 
    # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
    ciMult <- qt(conf.interval/2 + .5, datac$N-1)
    datac$ci <- datac$se * ciMult

    return(datac)
}
```

## Prep data
```{r}
l1 <- read.csv("~/Documents/College/AppliedMathConsulting/Lucchi2/lucchi2.csv")
l1 <- l1[c(1:463),c(1:6)]
l1$woodnumf <- as.factor(l1$woodnum)
l1summ <- summarySE(l1, measurevar="measure", groupvars=c("woodtype","woodnum","woodpiece","side","force","woodnumf"))
l1summ$forcef <- as.factor(l1summ$force)

#test samples for each force level
test <- l1summ %>%
	dplyr::group_by(woodnum, forcef,N) %>%
	dplyr::summarize(sampsize = sum(N))
#20 is tinytinytiny, drop it.
l1 <- l1[which(l1$force!=20),]
l1summ <-  l1summ[which(l1summ$force!=20),]
```

## Investigating 
```{r pressure, echo=FALSE}

# ggplot(l1[which(l1$woodtype=="s"),], aes(x=force, y=measure)) +
# 	geom_point(aes(color=woodnum)) +
# 	geom_smooth()+
# 	#stat_smooth(formula = y ~ I(1/x), method=glm) +
# 	scale_x_continuous(name="Force Applied (Newtons)") +
# 	scale_y_continuous(name="Lucchi Value")

# ggplot(l1summ, aes(x=force, y=measure, color=woodnum)) +
# 	geom_line() +
# 	geom_errorbar(aes(ymin=measure-se, ymax=measure+se), width=0.1) +
# 	scale_x_continuous(name="Force Applied (Newtons)") +
# 	scale_y_continuous(name="Lucchi Value") +
# 	facet_wrap(~woodpiece)

ggplot(l1summ[which(l1summ$force>2),], aes(x=force, y=se, color=woodnum)) +
	geom_point() +
	facet_wrap(~woodtype) +
	ggtitle("Standard Error in Lucchi Measurements by Force Applied \n(All Wood Samples)") +
	xlab("Force Applied to Sensors (Newtons)") + ylab("Standard Error for Wood Sample")

ggplot(l1summ, aes(x=forcef, y=se)) +
	geom_violin() +
	facet_wrap(~woodtype) +
	ggtitle("Standard Error in Lucchi Measurements by Force Applied \n(All Wood Samples)") +
	xlab("Force Applied to Sensors (Newtons)") + ylab("Standard Error for Wood Sample")

```


```



```{r}
single.lm <- lm(formula = measure ~ I(1/force) + num, data= l1)
summary(single.lm) #F=156.3 // AdjR2=0.5155 

```


```{r}
ggplot()

```



